### ISSUE TITLE
How to avoid handler name clashes across roles in the same play.

### ISSUE THREAD

**Issue by NeilDavisNPS** [ansible-lockdown/RHEL9-CIS#223]
**Question**
This is a question about usage, and possibly style in respect of plays within a playbook. 
One of the tasks in the post section of the role, is the following:
- name: Flush handlers
    ansible.builtin.meta: flush_handlers
This ,if I have understood the description, causes all handlers in a play that have a notify set to be actioned.. irrespective of the role in which the handler is defined. I tripped over having a user defined handler with one of the same name as in the rhel9 role ( "Restart sshd"), so it ran before the other role itself had run causing the play to fail.

Is it "good form" to run the rhel9cis role in it's own play? Is there a clean way to namespace the tasks so that they do not clash?

**Environment (please complete the following information):**

- Ansible Version: [2.16.9]
- Host Python Version: [3.11 ]
- Ansible Server Python Version: [3.9]
- Additional Details:

**Comment by uk-bolly** [comment]
hi @NeilDavisNPS 

Great question, As you have mentioned i would suggest the same, to run it as its own play or the order in which you run your roles.
Due to the  number of changes/tasks in these roles and the way the vendors give updates, i would run these individually unless you are able to keep on top of the changes as part of your solution.

Kindest regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @NeilDavisNPS 

Thank you again for the question. This does appear that there is no further correspondence on this issue. I will there fore close this. Please feel free to reopen if this is not the case.

many thanks

uk-bolly
