### ISSUE TITLE
Allow playbooks to run against CentOS stream 9

### ISSUE THREAD

**Issue by carlosrodfern** [ansible-lockdown/RHEL9-CIS#75]
## Feature Request or Enhancement

The playbook explicitly prevents runs against CentOS Stream 9, however, it does work.

**Summary of Request**
Remove constraint on CentOS Stream 9

**Describe alternatives you've considered**

**Suggested Code**

Adding a `CentOS.yaml` var file, with the corresponding data, and removing the check that purposely excludes CentOS Stream 9, allows the playbook to harden the machine, and gets pretty good results with the default settings.

```
'The post remediation results are: Count: 613, Failed: 47, Duration: 30.235s.'
```

```diff
diff --git a/tasks/main.yml b/tasks/main.yml
index 2bb0f3f..2be091c 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -3,7 +3,7 @@
 
 - name: Check OS version and family
   ansible.builtin.assert:
-      that: (ansible_distribution != 'CentOS' and ansible_os_family == 'RedHat' or ansible_os_family == "Rocky") and ansible_distributi
on_major_version is version_compare('9', '==')
+      that: (ansible_os_family == 'RedHat' or ansible_os_family == "Rocky") and ansible_distribution_major_version is version_compare('9', '==')
       fail_msg: "This role can only be run against Supported OSs. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
       success_msg: "This role is running against a supported OS {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
   when:
diff --git a/tasks/section_1/cis_1.2.x.yml b/tasks/section_1/cis_1.2.x.yml
index 2501732..ec62357 100644
--- a/tasks/section_1/cis_1.2.x.yml
+++ b/tasks/section_1/cis_1.2.x.yml
@@ -25,7 +25,8 @@
       - rhel9cis_rule_1_2_1
       - ansible_distribution == "RedHat" or
         ansible_distribution == "Rocky" or
-        ansible_distribution == "AlmaLinux"
+        ansible_distribution == "AlmaLinux" or
+        ansible_distribution == "CentOS"
   tags:
       - level1-server
       - level1-workstation
```

And then,

```
$ cat vars/CentOS.yml 

os_gpg_key_pubkey_name: centos-gpg-keys
os_gpg_key_pubkey_content: "builder@centos.org 9.0"
```

The ansible facts for CentOS Stream 9 looks like this:
```
"ansible_distribution": "CentOS",
"ansible_distribution_major_version": "9",
"ansible_distribution_release": "Stream",
"ansible_distribution_version": "9",
"ansible_os_family": "RedHat"
```

**Comment by carofe82** [comment]
Is there any reason to prevent the run on CentOS Stream 9? I understand that Lockdown company may want to limit what they want to officially support, but as an Open Source project it appears rather an artificial constraint.

**Comment by uk-bolly** [comment]
hi @carofe82 

Thank you for raising this issue and the recent PR. It is from feedback that we can improve this content.
We have looked at supporting stream on others OSs, we have found that stream is slightly more bleeding edge and may contain different packages and configuration options to the more mainline versions. Meaning in some cases we would end up managing specific setting in some cases that may only work with CentOS stream.
If a client was to request this we would probably add it as they do purchase the privilege in some cases.
If we were to allow Centos to be run and incorporate the settings you have suggested we would be expected (despite stating otherwise) to provide updates for the issues that may arise purely for the one OS.
I will raise this discussion and see the general consensus from the rest of the team.
We will get back to you as soon as we have discussed this.
Once again many thanks for raising this.

uk-bolly

**Comment by carofe82** [comment]
Thank you @uk-bolly  for looking into this.

**Comment by uk-bolly** [comment]
hi @carlosrodfern 

This should now work and is currently in the devel branch, I have added the centos key you have provided and although added CentOS remains unsupported for those reasons above.
You can turn off the OS check by changing the variable
```
os_check: false
```
This will skip the OS check but should still incorporate the CentOS variables you have provided.

Thank you again for taking the time to raise.

uk-bolly

**Comment by carlosrodfern** [comment]
@uk-bolly , I just finished testing it. It works well, as expected. Thank you!

**Comment by carlosrodfern** [comment]
@uk-bolly , the `Readme.md` has a typo, though. It says `check_os` but it is `os_check`.

**Comment by carlosrodfern** [comment]
This issue is solved. Closing.
