### ISSUE TITLE
error when scanning a server that is offline

### ISSUE THREAD

**Issue by jamhulk** [ansible-lockdown/RHEL9-CIS#92]
as stated, an error encountered when scanning a server that is offline or not connected to the internet.

**Comment by uk-bolly** [comment]
hi @jamhulk 

Thank you for raising the issue, please can you provide some further information?

version of ansible
version on python

which control it stops at?

In short there are multiple things that will fail is the system doesn't meet all the pre-requisites and it is not connected to the internet. The baseline itself does extensive testing so it is setup to work with each different setup (especially on brownfield servers or those not connected to the internet).

Ansible provides each control with a title to help explain what it is trying to achieve at each step and if you have set a control to run that has prereqs it will try to add them on your behalf. In your case you will have to ensure you have the control you want and the prereqs are met in each case.

I hope that makes sense

many t hanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @jamhulk 

I have looked at this a little further already, as this is mentioned only when running a scan ( i assume it should be for the audit component only?). If this is the case we should move the discussion to the audit repository.

CIS benchmarks require several tests that would be needed in order to pass or fail, with each control having the ability to be enabled or disabled the following should be turned off.

Without having knowledge on your configurations, I am assuming the following.

1. You have added the goss binary and the audit content manually to the system or used the copy options to do so within remediation?
2. You don't have a satellite server or any update server to test for any updates

Your main culprit for rhel9 in the audit will be

```rhel9cis_rule_1_9```

If other OS remediation benchmarks are also being used they will do other checks that may need to be disabled.

This asks the system to ensure there are no outstanding updates available by running dnf to test, if this is not connected this will fail i'm afraid.

Please feel free to drop by discord server to discuss further with us or any other members of the community on how they are approaching any issue that you maybe experiencing.

If i have mis-assumed, if you can please let us have further information about your setup, variables being used from default and maybe an output of the actual error.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @jamhulk 

I hope this is now working for you, i have noticed this is also raised on another repo, which has further feedback regarding prerequisites that are required. will need to be installed if the system is disconnected.
If you are still seeing problems, please let us know that all the required packages are added to the system and some log extraction of the failures.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @jamhulk 

I will close this request as stale, please feel free to open a new issue if you are able provide further information.

Many thanks

uk-bolly
